### ISSUE TITLE
Doesn't add @storybook/vue to devDependencies?

### ISSUE THREAD

**Issue by nickforddesign** [storybookjs/vue-cli-plugin-storybook#47] opened 2019-02-19 16:27 UTC
Seems wrong for this plugin to not add `@storybook/vue` to devDependencies. It gets installed because it's a dependency of this plugin but it's not actually saved to the new project, so if you have to delete `node_modules` and reinstall, your project is broken.

**Comment by pksunkara** [comment] 2019-02-20 01:55
This plugin would add itself to devDependencies. So, if you reinstall node modules, then `@storybook/vue` would still be installed because it's a dependency of this plugin. I don't understand why the issue is occurring for you.

**Comment by pksunkara** [comment] 2019-03-09 16:27
@nickforddesign Any update on this? I will close this soon if none.

**Comment by backbone87** [comment] 2019-03-10 00:25
there is a certain point to this and while adding @storybook/vue to devDeps would work, i dont think this is the best approach. the thing is that you do direct imports on @storybook/vue in your stories/config, so in an ideal world you should add it to the deps. the way i would go, is to reexport the @storybook/vue stuff from the plugin, so you would import from the plugin not @storybook/vue, but then we tie the plugin version to @storybook/vue's version.

**Comment by backbone87** [comment] 2019-03-10 00:57
if we go for the reexport version, i would wait until the TS migration is done for storybook so its easier to reexport the needed types too

**Comment by nickforddesign** [comment] 2019-03-11 14:39
yeah that was pretty much the issue. having to include
```js
/* eslint-disable import/no-extraneous-dependencies */
```
is a hacky workaround, and I am 99% sure that when I reinstalled node dependencies that `@storybook/vue` was not installed.

**Comment by supermonkeyz** [comment] 2019-08-02 13:04
Maybe put `@storybook/vue` outside plugin is better? if i want upgrade `@storybook/vue`，i must remove `@storybook` from  plugin's node_modules

**Comment by pksunkara** [comment] 2020-01-13 06:24
I made @storybook/vue a peer dependency in v1. This should be solved now.

**Closed by pksunkara** 2020-01-13 06:24 UTC
